name: cnn_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.19
  - ipykernel=7.2.0
  - jupyter=1.1.1

  - numpy=1.26.4
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - seaborn=0.13.2

  - polars=1.38.1
  - pyarrow=23.0.1

  - pytorch=2.10.0
  - faiss-cpu=1.9.0

  - python-louvain=0.16
  - pyvis=0.3.2

  - pip

  - pip:
      - node2vec==0.5.0